### ISSUE TITLE
Shrinked social template?

### ISSUE THREAD

**Issue by 0vermind** [pinax/pinax-project-social#6]
Hi, sorry for the noob question but, this pinax-project-social has nothing to do with the old social-project here: http://pinax-social.stackato.com/ It's seems a shrinked version of the old project.
Am I'm correct? 
Is there any docs or pinax community where I can find what's is happening?
All the features of the pinax framework have been dropped?

**Comment by ossanna16** [comment]
@0vermind This issue is quite old so I was wondering if your question has been answered by now. If not, please feel free to join our new Pinax project Slack channel http://slack.pinaxproject.com :)

**Comment by jtauber** [comment]
We're rebuilding the social functionality from the ground up but given this repo is so old and so many things have changed. I think we should delete this repo.

Further work on the social starter project will happen on the https://github.com/pinax/pinax-starter-projects repo and I'm not sure there's anything in this repo worth keeping.
